version: "3.3"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: nextcreative-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www:rw
      - ./docker-compose/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - nextcreativeNetwork
  nginx:
    image: nginx:1.17-alpine
    container_name: nextcreative-nginx
    restart: unless-stopped
    ports:
      - 8005:8005
      - 80:80
      - 8001:8001
    volumes:
      - ./:/var/www:rw
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - nextcreativeNetwork
networks:
  nextcreativeNetwork:
    driver: bridge
